# Generated by Django 3.0.3 on 2020-03-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_prereq'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='coreqCount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
