# Generated by Django 3.0.4 on 2020-03-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TransferCredit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('courseDept', models.CharField(blank=True, max_length=4, null=True)),
                ('name', models.CharField(max_length=50)),
                ('equivalentToID', models.CharField(blank=True, max_length=4, null=True)),
                ('equivalentToDept', models.CharField(blank=True, max_length=4, null=True)),
                ('requiredScore', models.CharField(blank=True, max_length=5, null=True)),
                ('equivalentToCat', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
