# Generated by Django 3.0.2 on 2020-04-27 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='semesterOption',
            field=models.CharField(default='Fall', max_length=10),
        ),
    ]
