# Generated by Django 3.0.4 on 2020-04-14 17:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='completedCourses',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
