# Generated by Django 3.0.4 on 2020-04-30 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='semesterHours',
            field=models.PositiveSmallIntegerField(default=15),
        ),
    ]
