# Generated by Django 3.0.4 on 2020-04-28 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='semesterOption',
            field=models.CharField(choices=[('Fall', ' Fall'), ('Spring', 'Spring')], default='Fall', max_length=10),
        ),
    ]
