# Generated by Django 3.0.4 on 2020-04-30 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_session_semesterhours'),
        ('session', '0002_auto_20200427_2014'),
    ]

    operations = [
    ]
