# Generated by Django 3.0.4 on 2020-04-14 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20200407_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='last_visit',
            field=models.DateField(auto_now=True),
        ),
    ]
