# Generated by Django 3.0.4 on 2020-04-16 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_auto_20200414_1254'),
        ('session', '0003_session_last_visit'),
    ]

    operations = [
    ]
