# Generated by Django 3.0.4 on 2020-04-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='sessionPIN',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
