# Generated by Django 3.0.4 on 2020-04-07 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200407_1352'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Session',
        ),
    ]
