# Generated by Django 3.0.2 on 2020-02-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='year',
            field=models.CharField(max_length=100),
        ),
    ]
