# Generated by Django 3.0.2 on 2020-03-17 14:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='collegeOf',
            field=models.TextField(default=2015),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='degree',
            name='specialOption',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='degree',
            name='catalogYear',
            field=models.IntegerField(),
        ),
    ]
