# Generated by Django 3.0.2 on 2020-03-14 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0002_auto_20200314_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='courseList',
            field=models.TextField(),
        ),
    ]
