# Generated by Django 3.0.2 on 2020-02-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0002_degree_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='year',
            field=models.CharField(default='2020', max_length=100),
        ),
    ]
