# Generated by Django 3.0.2 on 2020-03-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0002_auto_20200317_0938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.TextField(),
        ),
    ]
