# Generated by Django 3.0.2 on 2020-03-17 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0003_auto_20200317_1156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='collegeOf',
        ),
    ]
