# Generated by Django 3.0.2 on 2020-03-14 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0003_auto_20200314_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='courseList',
        ),
    ]
