# Generated by Django 3.0.2 on 2020-03-17 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0004_remove_degree_collegeof'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='collegeName',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
