# Generated by Django 3.0.2 on 2020-03-17 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0005_degree_collegename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree',
            old_name='specialOption',
            new_name='specialty',
        ),
    ]
