# Generated by Django 3.0.2 on 2020-03-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0006_auto_20200317_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='collegeName',
        ),
        migrations.RemoveField(
            model_name='degree',
            name='specialty',
        ),
        migrations.AlterField(
            model_name='degree',
            name='catalogYear',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='degree',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
