# Generated by Django 3.0.2 on 2020-03-17 21:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0007_auto_20200317_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='CollegeName',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
