# Generated by Django 3.0.2 on 2020-03-17 22:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0008_degree_collegename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='CollegeName',
        ),
        migrations.AddField(
            model_name='degree',
            name='CollegeInfo',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
