# Generated by Django 3.0.2 on 2020-03-18 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0009_auto_20200317_1725'),
    ]

    operations = [
        migrations.RenameField(
            model_name='degree',
            old_name='CollegeInfo',
            new_name='CollegeName',
        ),
    ]
