# Generated by Django 3.0.2 on 2020-03-18 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0010_auto_20200317_2355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='degree',
            name='CollegeName',
        ),
    ]
