# Generated by Django 3.0.2 on 2020-03-18 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('degrees', '0012_degree_collegename'),
    ]

    operations = [
        migrations.AddField(
            model_name='degree',
            name='specialty',
            field=models.CharField(default='Null', max_length=100),
            preserve_default=False,
        ),
    ]
